"""Added new arguments and support

Revision ID: 1e86ed3cc250
Revises: 
Create Date: 2024-03-18 20:12:12.936717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e86ed3cc250'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('towerinfo', sa.Column('effectiveRadiatedPower', sa.String(), nullable=True))
    op.add_column('towerinfo', sa.Column('downtilt', sa.String(), nullable=True))
    op.add_column('towerinfo', sa.Column('downtiltDirection', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('towerinfo', 'downtiltDirection')
    op.drop_column('towerinfo', 'downtilt')
    op.drop_column('towerinfo', 'effectiveRadiatedPower')
    # ### end Alembic commands ###
