"""changing deadline to a string object

Revision ID: 1f32126b9e35
Revises: feddffaf6121
Create Date: 2024-03-20 19:46:59.687154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f32126b9e35'
down_revision = 'feddffaf6121'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
