"""Initial migration

Revision ID: 2b4d081cc72f
Revises: 
Create Date: 2023-07-06 19:35:32.545535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b4d081cc72f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('KML',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('served', sa.Boolean(), nullable=True),
    sa.Column('wireless', sa.Boolean(), nullable=True),
    sa.Column('lte', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('coveredLocations', sa.String(), nullable=True),
    sa.Column('maxDownloadNetwork', sa.String(), nullable=True),
    sa.Column('maxDownloadSpeed', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('fabric',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('address_primary', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('zip_suffix', sa.String(), nullable=True),
    sa.Column('unit_count', sa.Integer(), nullable=True),
    sa.Column('bsl_flag', sa.String(), nullable=True),
    sa.Column('building_type_code', sa.String(), nullable=True),
    sa.Column('land_use_code', sa.Integer(), nullable=True),
    sa.Column('address_confidence_code', sa.String(), nullable=True),
    sa.Column('country_geoid', sa.String(), nullable=True),
    sa.Column('block_geoid', sa.String(), nullable=True),
    sa.Column('h3_9', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('mbt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tile_data', sa.LargeBinary(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('zoom_level', sa.Integer(), nullable=True),
    sa.Column('tile_column', sa.Integer(), nullable=True),
    sa.Column('tile_row', sa.Integer(), nullable=True),
    sa.Column('tile_data', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vt')
    op.drop_table('user')
    op.drop_table('mbt')
    op.drop_table('fabric')
    op.drop_table('KML')
    # ### end Alembic commands ###
