"""add folder lineage

Revision ID: 385ef81c2caa
Revises: e6c3d4cc860d
Create Date: 2026-06-11 01:13:12.469883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385ef81c2caa'
down_revision = 'e6c3d4cc860d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folder', sa.Column('source_folder_id', sa.Integer(), nullable=True))
    op.create_foreign_key('folder_source_folder_id_fkey', 'folder', 'folder', ['source_folder_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('folder_source_folder_id_fkey', 'folder', type_='foreignkey')
    op.drop_column('folder', 'source_folder_id')
    # ### end Alembic commands ###
