"""Added deadline column to folder

Revision ID: 3e0ebef6b5e1
Revises: f2a2ba4afe17
Create Date: 2024-02-28 20:59:09.701399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e0ebef6b5e1'
down_revision = 'f2a2ba4afe17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filing')
    op.drop_table('organization')
    op.add_column('folder', sa.Column('deadline', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folder', 'deadline')
    op.create_table('organization',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('organization_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('brand_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='organization_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('filing',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('deadline', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name='filing_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='filing_pkey')
    )
    # ### end Alembic commands ###
