"""adding deadline field of type string

Revision ID: 4de22499eacc
Revises: fc901297b2f1
Create Date: 2024-03-20 20:07:33.047762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4de22499eacc'
down_revision = 'fc901297b2f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folder', sa.Column('deadline', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folder', 'deadline')
    # ### end Alembic commands ###
