"""add filing status to folder

Revision ID: 8e52e1e309c5
Revises: 9ecd053152a0
Create Date: 2026-06-10 16:28:22.455888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e52e1e309c5'
down_revision = '9ecd053152a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folder', sa.Column('status', sa.String(), server_default='open', nullable=False))
    op.add_column('folder', sa.Column('filed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folder', 'filed_at')
    op.drop_column('folder', 'status')
    # ### end Alembic commands ###
