"""add service plans

Revision ID: 93e47504d74d
Revises: 8e52e1e309c5
Create Date: 2026-06-10 16:39:54.826936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e47504d74d'
down_revision = '8e52e1e309c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tech_code', sa.Integer(), nullable=False),
    sa.Column('max_download', sa.Integer(), nullable=False),
    sa.Column('max_upload', sa.Integer(), nullable=False),
    sa.Column('low_latency', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('category', sa.String(length=1), server_default='X', nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('file', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key('file_plan_id_fkey', 'file', 'service_plan', ['plan_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('file_plan_id_fkey', 'file', type_='foreignkey')
    op.drop_column('file', 'plan_id')
    op.drop_table('service_plan')
    # ### end Alembic commands ###
