"""trying to change deadline to string tyep

Revision ID: acdc50d352eb
Revises: 1f32126b9e35
Create Date: 2024-03-20 19:58:41.439087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acdc50d352eb'
down_revision = '1f32126b9e35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
