"""Initial migration

Revision ID: b7c028b5a36a
Revises: 
Create Date: 2024-07-28 20:56:24.480788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7c028b5a36a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('primary_city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('zip_code_suffix', sa.String(), nullable=True),
    sa.Column('unit_count', sa.String(), nullable=True),
    sa.Column('building_type_code', sa.String(), nullable=True),
    sa.Column('non_bsl_code', sa.String(), nullable=True),
    sa.Column('bsl_lacks_address_flag', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('address_id', sa.String(), nullable=True),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('category_code', sa.String(), nullable=True),
    sa.Column('location_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fabric_data_temp',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('address_primary', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('zip_suffix', sa.String(), nullable=True),
    sa.Column('unit_count', sa.Integer(), nullable=True),
    sa.Column('bsl_flag', sa.String(), nullable=True),
    sa.Column('building_type_code', sa.String(), nullable=True),
    sa.Column('land_use_code', sa.Integer(), nullable=True),
    sa.Column('address_confidence_code', sa.String(), nullable=True),
    sa.Column('country_geoid', sa.String(), nullable=True),
    sa.Column('block_geoid', sa.String(), nullable=True),
    sa.Column('h3_9', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('fcc_rel', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('brand_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('folder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tower_name', sa.String(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('celerytaskinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('runtime', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('editfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('maxDownloadSpeed', sa.Integer(), nullable=True),
    sa.Column('maxUploadSpeed', sa.Integer(), nullable=True),
    sa.Column('techType', sa.Integer(), nullable=True),
    sa.Column('latency', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('computed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mbtiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tile_data', sa.LargeBinary(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rasterdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_data', sa.LargeBinary(), nullable=True),
    sa.Column('transparent_image_data', sa.LargeBinary(), nullable=True),
    sa.Column('loss_color_mapping', sa.JSON(), nullable=True),
    sa.Column('north_bound', sa.String(), nullable=True),
    sa.Column('south_bound', sa.String(), nullable=True),
    sa.Column('east_bound', sa.String(), nullable=True),
    sa.Column('west_bound', sa.String(), nullable=True),
    sa.Column('tower_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tower_id'], ['tower.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('towerinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('radius', sa.String(), nullable=True),
    sa.Column('antennaHeight', sa.String(), nullable=True),
    sa.Column('antennaTilt', sa.String(), nullable=True),
    sa.Column('horizontalFacing', sa.String(), nullable=True),
    sa.Column('floorLossRate', sa.String(), nullable=True),
    sa.Column('tower_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tower_id'], ['tower.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fabric_data',
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('address_primary', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('zip_suffix', sa.String(), nullable=True),
    sa.Column('unit_count', sa.Integer(), nullable=True),
    sa.Column('bsl_flag', sa.String(), nullable=True),
    sa.Column('building_type_code', sa.String(), nullable=True),
    sa.Column('land_use_code', sa.Integer(), nullable=True),
    sa.Column('address_confidence_code', sa.String(), nullable=True),
    sa.Column('country_geoid', sa.String(), nullable=True),
    sa.Column('block_geoid', sa.String(), nullable=True),
    sa.Column('h3_9', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('fcc_rel', sa.String(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_editfile_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('editfile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['editfile_id'], ['editfile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kml_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('served', sa.Boolean(), nullable=True),
    sa.Column('wireless', sa.Boolean(), nullable=True),
    sa.Column('lte', sa.Boolean(), nullable=True),
    sa.Column('coveredLocations', sa.String(), nullable=True),
    sa.Column('maxDownloadNetwork', sa.String(), nullable=True),
    sa.Column('maxDownloadSpeed', sa.Integer(), nullable=True),
    sa.Column('maxUploadSpeed', sa.Integer(), nullable=True),
    sa.Column('techType', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('address_primary', sa.String(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('latency', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vector_tiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('zoom_level', sa.Integer(), nullable=True),
    sa.Column('tile_column', sa.Integer(), nullable=True),
    sa.Column('tile_row', sa.Integer(), nullable=True),
    sa.Column('tile_data', sa.LargeBinary(), nullable=True),
    sa.Column('mbtiles_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mbtiles_id'], ['mbtiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vector_tiles')
    op.drop_table('kml_data')
    op.drop_table('file_editfile_link')
    op.drop_table('fabric_data')
    op.drop_table('towerinfo')
    op.drop_table('rasterdata')
    op.drop_table('mbtiles')
    op.drop_table('file')
    op.drop_table('editfile')
    op.drop_table('celerytaskinfo')
    op.drop_table('user')
    op.drop_table('tower')
    op.drop_table('folder')
    op.drop_table('organization')
    op.drop_table('fabric_data_temp')
    op.drop_table('challenge_locations')
    # ### end Alembic commands ###
