"""add per-file coverage buffer

Revision ID: e6c3d4cc860d
Revises: a1f7c30d9e42
Create Date: 2026-06-10 21:58:18.949023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6c3d4cc860d'
down_revision = 'a1f7c30d9e42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('coverage_buffer_m', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'coverage_buffer_m')
    # ### end Alembic commands ###
