"""deadline field to folder class added

Revision ID: feddffaf6121
Revises: 3e0ebef6b5e1
Create Date: 2024-03-18 20:01:31.195441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feddffaf6121'
down_revision = '3e0ebef6b5e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
