version: '3'
services:
  frontend:
    build:
      context: ./front_end # Path to the front-end Dockerfile
    ports:
      - 3000:3000 # Map port 3000 inside the container to port 3000 on the host
  
  backend:
    build:
      context: ./back-end # Path to the back-end Dockerfile
    ports:
      - 8000:8000 # Map port 8000 inside the container to port 8000 on the host
      
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=db123
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432  # Map port 5432 inside the container to port 5432 on the host

  redis:
    image: redis:latest
    ports:
      - 6379:6379
