services:


  backend:
    image: ${DOCKER_IMAGE_BACKEND}
    network_mode: host
    build:
      context: ./back-end
      dockerfile: Dockerfile.backend
    command: gunicorn routes:app -b 0.0.0.0:8000 -w 4 --log-level debug --reload
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_TOKEN_LOCATION=${JWT_TOKEN_LOCATION}
      - JWT_ACCESS_COOKIE_NAME=${JWT_ACCESS_COOKIE_NAME}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USE_TLS=${MAIL_USE_TLS}
      - MAIL_USE_SSL=${MAIL_USE_SSL}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
      - DEVELOP_BACKEND_PORT=${DEVELOP_BACKEND_PORT}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - IN_PRODUCTION=1
    volumes:
      - ./back-end:/app
    expose:
      - ${DEVELOP_BACKEND_PORT}

  frontend:
    image: ${DOCKER_IMAGE_FRONTEND}
    network_mode: host
    build: ./front-end
    volumes:
      - ./front-end:/app
    depends_on:
      - backend
    expose:
      - ${DEVELOP_FRONTEND_PORT}


  nginx:
    image: ${DOCKER_IMAGE_NGINX}
    network_mode: host
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    container_name: nginx-proxy
    environment:
      - SSL_PASSWORD_FILE=/ssl/${SSL_PASSPHRASE_FILE}
    # ports:
    #   - "${NGINX_HTTP_PORT}:80"
    #   - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - ${NGINX_CONF_PROD}:/etc/nginx/conf.d/default.conf
      - ${SSL_PATH}/${SSL_CERT}:/etc/nginx/ssl/${SSL_CERT}
      - ${SSL_PATH}/${SSL_KEY}:/etc/nginx/ssl/${SSL_KEY}
      - ${SSL_PATH}/${SSL_PASSPHRASE_FILE}:/ssl/${SSL_PASSPHRASE_FILE}
    depends_on:
      - backend
      - frontend

