services:
  work:
    image: ghcr.io/spin-vt/backend
    build: 
      context: ./back-end
      dockerfile: Dockerfile.worker
    command: celery -A controllers.celery_controller.celery_config.celery worker --loglevel=DEBUG
    volumes:
      - ./back-end:/app
    depends_on:
      - redis
  
  backend:
    image: ghcr.io/spin-vt/worker
    build:
      context: ./back-end
      dockerfile: Dockerfile.backend
    command: gunicorn routes:app -b 0.0.0.0:8000 -w 4 --log-level debug --reload
    volumes:
      - ./back-end:/app
    depends_on:
      - db
      - redis
    expose:
      - 8000

  frontend:
    image: ghcr.io/spin-vt/frontend
    build: ./front-end
    volumes:
      - ./front-end:/app
    depends_on:
      - backend
    expose:
      - 3000

  nginx:
    image: ghcr.io/spin-vt/my-nginx
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    container_name: nginx-proxy
    depends_on:
      - backend
      - frontend

