version: '3'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: db123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
  
  celery:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    command: celery -A routes.celery worker --loglevel=DEBUG
    volumes:
      - ./back-end:/app
    depends_on:
      - redis
  
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    volumes:
      - ./back-end:/app
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=postgres
  
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    volumes:
      - ./front-end:/app
    ports:
      - '3000:3000'

volumes:
  postgres_data: {}
