version: '3.8'

services:
  nginx:
    image: ${NGINX_IMAGE}
    container_name: nginx-proxy
    environment:
      - SSL_PASSWORD_FILE=/ssl/${SSL_PASSPHRASE_FILE}
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - ${NGINX_CONF_DEV}:/etc/nginx/conf.d/default.conf
      - ${SSL_PATH}/${SSL_CERT}:/etc/nginx/ssl/${SSL_CERT}
      - ${SSL_PATH}/${SSL_KEY}:/etc/nginx/ssl/${SSL_KEY}
      - ${SSL_PATH}/${SSL_PASSPHRASE_FILE}:/ssl/${SSL_PASSPHRASE_FILE}
    depends_on:
      - backend
      - frontend

