name: Build and Push Docker Images to GitHub Registry

# on:
#   push:
#     branches:
#       - main

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Login to GitHub Docker Registry
      run: echo "${{secrets.DOCKER_LOGIN_TOKEN}}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker images using docker-compose.prod.yml
      run: docker-compose -f docker-compose.prod.yml build

    - name: Push Docker images to registry
      run: |
        docker push ghcr.io/spin-vt/worker:latest
        docker push ghcr.io/spin-vt/backend:latest
        docker push ghcr.io/spin-vt/frontend:latest
